/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Management API
 * API for managing users with role-based access control
 * OpenAPI spec version: 1.0
 */
import type { CreateUserDtoRole } from './createUserDtoRole';

export interface CreateUserDto {
  /** The name of the user */
  name: string;
  /** The email of the user */
  email: string;
  /**
   * The password of the user
   * @minLength 8
   */
  password: string;
  /** The role of the user */
  role: CreateUserDtoRole;
}
