/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Management API
 * API for managing users with role-based access control
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** The email of the user */
  email: string;
  /** The password of the user */
  password: string;
}
