/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Management API
 * API for managing users with role-based access control
 * OpenAPI spec version: 1.0
 */

/**
 * The role of the user
 */
export type UpdateUserDtoRole = typeof UpdateUserDtoRole[keyof typeof UpdateUserDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserDtoRole = {
  admin: 'admin',
  manager: 'manager',
  user: 'user',
} as const;
