/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Management API
 * API for managing users with role-based access control
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type ApiResponseDtoData = { [key: string]: unknown } | null;
