/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * User Management API
 * API for managing users with role-based access control
 * OpenAPI spec version: 1.0
 */
import type { ApiResponseDtoData } from './apiResponseDtoData';

export interface ApiResponseDto {
  error: boolean;
  message: string;
  /** @nullable */
  data: ApiResponseDtoData;
}
